volumes:
  postgres_volume:
  frontend_volume:

services:

  backend_gateway:
    container_name: backend-gateway
    image: ghostblade3301/monitoring_gateway:latest
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    expose:
      - 80

  backend_report:
    container_name: backend-report
    image: ghostblade3301/monitoring_report:latest
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    expose:
      - 80

  frontend:
    container_name: frontend
    image: ghostblade3301/monitoring_frontend:latest
    volumes:
        - frontend_volume:/app/

  postgres:
    image: postgres:13.3-alpine
    container_name:  postgres
    restart: always
    volumes:
       - postgres_volume:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:alpine
    expose:
      - 6379

  nginx:
    container_name: nginx
    depends_on:
      - backend_gateway
      - backend_report
      - frontend
    restart: unless-stopped
    image: nginx:1.25
    volumes:
      - frontend_volume:/opt/monitoring/frontend/build/ 
      - /home/code/infra/nginx_prod.conf:/etc/nginx/conf.d/default.conf
      - /home/code/infra/fullchain.pem:/etc/ssl/fullchain.pem
      - /home/code/infra/privkey.pem:/etc/ssl/privkey.pem
      - /home/code/infra/options-ssl-nginx.conf:/etc/ssl/options-ssl-nginx.conf
      - /home/code/infra/ssl-dhparams.pem:/etc/ssl/ssl-dhparams.pem
    ports:
      - "80:80"
      - "443:443"
