volumes:
  postgres_volume:

services:

  backend-gateway:
    container_name: backend-gateway
    build:
      context: ../
      dockerfile: infra/Dockerfile_backend_gateway
    depends_on:
      - postgres
      - redis
      - backend-report
    environment:
      - SERVER_PORT=8080
      - REPORT_SERVICE_URL=http://backend-report:9090
    env_file:
      - .env
    expose:
      - 8080
    
  backend-report:
    container_name: backend-report
    build:
      context: ../
      dockerfile: infra/Dockerfile_backend_report
    depends_on:
      - postgres
      - redis
    environment:
      - SERVER_PORT=9090
    env_file:
      - .env
    expose:
      - 9090

  postgres:
    image: postgres:13.3-alpine
    container_name:  postgres
    restart: always
    volumes:
       - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:alpine
    expose:
      - 6379

  nginx:
    container_name: nginx
    depends_on:
      - backend-gateway
      - backend-report
    restart: unless-stopped
    image: nginx:1.25
    volumes:
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"