volumes:
  postgres_volume:
  frontend_volume:

services:

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: infra/Dockerfile_backend
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    expose:
      - 8080

  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: infra/Dockerfile_frontend
    depends_on:
      - postgres
      - redis
      - backend
    volumes:
        - frontend_volume:/frontend/
    expose:
      - 3000

  postgres:
    image: postgres:13.3-alpine
    container_name:  postgres
    restart: always
    volumes:
       - postgres_volume:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:alpine
    expose:
      - 6379

  nginx:
    container_name: nginx
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
