create table if not exists users
(
    id         BIGINT generated by default as identity NOT NULL PRIMARY KEY,
    first_name VARCHAR                                 NOT NULL,
    last_name  VARCHAR                                 NOT NULL,
    email      VARCHAR                                 NOT NULL UNIQUE,
    password   VARCHAR                                 NOT NULL,
    role       VARCHAR                                 NOT NULL
);
