spring:
  config:
    activate:
      on-profile: default
  mail:
    host: smtp.mail.ru
    port: 465
    username: indivmon@bk.ru
    password: KGsJXwXhwifnrzNSSNRQ
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/monitoring
    username: postgres
    password: postgres
# App Properties
app:
  token:
    signing:
      key: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  notifications:
    enabled: true
logging:
  level:
    org.springframework.mail: DEBUG
---
spring:
  # Конифиг для деплоя
  config:
    activate:
      on-profile: deploy
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mail:
    host: ${SMTP_SERVER}
    port: ${MAIL_SERVER_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
app:
  # Секретный  ключ для подписания токенов
  token:
    signing:
      key: ${SECURITY_KEY}
  notifications:
    # Отправляем уведомления на почту или нет
    enabled: false